services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:80"
    depends_on:
      - grpc_service

  grpc_service:
    build: ./grpc_service
    ports:
      - "50051:50051"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
