# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\"H\n\rUploadRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\"1\n\x0eUploadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0fRetrieveRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"2\n\nFileRecord\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\".\n\x10RetrieveResponse\x12\x1a\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0b.FileRecord2m\n\x0b\x46ileService\x12-\n\nUploadFile\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12/\n\x08GetFiles\x12\x10.RetrieveRequest\x1a\x11.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=22
  _globals['_UPLOADREQUEST']._serialized_end=94
  _globals['_UPLOADRESPONSE']._serialized_start=96
  _globals['_UPLOADRESPONSE']._serialized_end=145
  _globals['_RETRIEVEREQUEST']._serialized_start=147
  _globals['_RETRIEVEREQUEST']._serialized_end=183
  _globals['_FILERECORD']._serialized_start=185
  _globals['_FILERECORD']._serialized_end=235
  _globals['_RETRIEVERESPONSE']._serialized_start=237
  _globals['_RETRIEVERESPONSE']._serialized_end=283
  _globals['_FILESERVICE']._serialized_start=285
  _globals['_FILESERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
